# Generated by Django 3.2.4 on 2021-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="工作表名称")),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="工作表描述",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        null=True,
                        verbose_name="工作表标识",
                    ),
                ),
                (
                    "project_key",
                    models.CharField(default=0, max_length=32, verbose_name="项目key"),
                ),
            ],
        ),
    ]
