# Generated by Django 3.2.4 on 2021-09-16 12:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSheetField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="字段标识")),
                ("name", models.CharField(max_length=64, verbose_name="字段名")),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="字段填写说明",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STRING", "单行文本"),
                            ("TEXT", "多行文本"),
                            ("INT", "数字"),
                            ("DATE", "日期"),
                            ("DATETIME", "时间"),
                            ("DATETIMERANGE", "时间间隔"),
                            ("TABLE", "表格"),
                            ("SELECT", "单选下拉框"),
                            ("INPUTSELECT", "可输入单选下拉框"),
                            ("MULTISELECT", "多选下拉框"),
                            ("CHECKBOX", "复选框"),
                            ("RADIO", "单选框"),
                            ("MEMBER", "单选人员选择"),
                            ("MEMBERS", "多选人员选择"),
                            ("RICHTEXT", "富文本"),
                            ("FILE", "附件上传"),
                            ("CUSTOMTABLE", "自定义表格"),
                            ("TREESELECT", "树形选择"),
                            ("LINK", "链接"),
                            ("CUSTOM-FORM", "自定义表单"),
                            ("CASCADE", "级联"),
                        ],
                        default="STRING",
                        max_length=32,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[("COL_6", "半行"), ("COL_12", "整行")],
                        default="COL_6",
                        max_length=32,
                        verbose_name="布局",
                    ),
                ),
                (
                    "unique",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否唯一"
                    ),
                ),
                (
                    "validate_type",
                    models.CharField(
                        choices=[("OPTION", "可选"), ("REQUIRE", "必填")],
                        default="REQUIRE",
                        max_length=32,
                        verbose_name="校验规则",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CUSTOM", "自定义数据"),
                            ("API", "接口数据"),
                            ("DATADICT", "数据字典"),
                            ("RPC", "系统数据"),
                            ("WORKSHEET", "工作表"),
                        ],
                        default="CUSTOM",
                        max_length=32,
                        verbose_name="数据来源类型",
                    ),
                ),
                (
                    "api_instance_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="api实例主键"
                    ),
                ),
                (
                    "kv_relation",
                    jsonfield.fields.JSONCharField(
                        default={}, max_length=64, verbose_name="源数据的kv关系配置"
                    ),
                ),
                (
                    "default",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10000,
                        null=True,
                        verbose_name="默认值",
                    ),
                ),
                ("choice", jsonfield.fields.JSONField(default=[], verbose_name="选项")),
                ("meta", jsonfield.fields.JSONField(default={}, verbose_name="复杂描述信息")),
                ("worksheet_id", models.IntegerField(verbose_name="工作表id")),
            ],
        ),
    ]
