# Generated by Django 3.2.4 on 2021-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0003_alter_worksheetfield_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="fields",
            field=models.JSONField(default=[], verbose_name="字段的顺序, 按列表"),
        ),
    ]
