# Generated by Django 3.2.4 on 2021-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0004_worksheet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksheetfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("STRING", "单行文本"),
                    ("TEXT", "多行文本"),
                    ("INT", "数字"),
                    ("DATE", "日期"),
                    ("DATETIME", "时间"),
                    ("DATETIMERANGE", "时间间隔"),
                    ("TABLE", "表格"),
                    ("SELECT", "单选下拉框"),
                    ("INPUTSELECT", "可输入单选下拉框"),
                    ("MULTISELECT", "多选下拉框"),
                    ("CHECKBOX", "复选框"),
                    ("RADIO", "单选框"),
                    ("MEMBER", "单选人员选择"),
                    ("MEMBERS", "多选人员选择"),
                    ("RICHTEXT", "富文本"),
                    ("FILE", "附件上传"),
                    ("CUSTOMTABLE", "自定义表格"),
                    ("TREESELECT", "树形选择"),
                    ("LINK", "链接"),
                    ("CUSTOM-FORM", "自定义表单"),
                    ("CASCADE", "级联"),
                    ("AUTO-NUMBER", "自动编号"),
                    ("IMAGE", "图片上传"),
                ],
                default="STRING",
                max_length=32,
                verbose_name="字段类型",
            ),
        ),
    ]
