# Generated by Django 3.2.4 on 2021-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0006_auto_20211014_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheetfield",
            name="regex",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="正则校验规则关键字",
            ),
        ),
    ]
