# Generated by Django 3.2.4 on 2021-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0007_worksheetfield_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheetfield",
            name="tips",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="字段展示说明"
            ),
        ),
    ]
