# -*- coding: utf-8 -*-
WORKSHEET_DATA = {
    "id": 1,
    "creator": "admin",
    "create_at": "2021-09-18 15:51:22",
    "update_at": "2021-09-18 15:51:22",
    "updated_by": "admin",
    "is_deleted": False,
    "name": "test",
    "desc": "test_worksheet",
    "key": "test",
    "project_key": "test",
}

WORKSHEET_FIELD = {
    "worksheet_id": WORKSHEET_DATA["id"],
    "fields": [
        {
            "meta": {},
            "api_info": {},
            "choice": [],
            "kv_relation": {},
            "key": "shu_zi_1",
            "name": "数字1",
            "desc": "",
            "type": "INT",
            "layout": "COL_12",
            "validate_type": "OPTION",
            "source_type": "CUSTOM",
            "api_instance_id": 0,
            "default": "0",
            "worksheet_id": WORKSHEET_DATA["id"],
            "regex": "EMPTY",
        },
        {
            "meta": {},
            "api_info": {},
            "choice": [],
            "kv_relation": {},
            "create_at": "2022-01-27 15:37:28",
            "key": "shu_zi_2",
            "name": "数字2",
            "desc": "",
            "type": "INT",
            "layout": "COL_12",
            "validate_type": "OPTION",
            "source_type": "CUSTOM",
            "api_instance_id": 0,
            "default": "0",
            "worksheet_id": WORKSHEET_DATA["id"],
            "regex": "EMPTY",
        },
    ],
}
