# Generated by Django 3.2.4 on 2021-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "功能卡片"),
                    ("LIST", "列表"),
                    ("SHEET", "表单"),
                    ("GROUP", "分组"),
                ],
                max_length=32,
                verbose_name="页面类型",
            ),
        ),
    ]
