# Generated by Django 3.2.4 on 2021-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_alter_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="display_role",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="可见范围"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("CMDB", "CMDB业务公用角色"),
                    ("GENERAL", "通用角色表"),
                    ("OPEN", "不限"),
                    ("PERSON", "个人"),
                    ("ORGANIZATION", "组织架构"),
                    ("INVISIBLE", "不可见"),
                    ("API", "第三方系统"),
                ],
                default="OPEN",
                max_length=32,
                verbose_name="可见范围类型",
            ),
        ),
    ]
