# Generated by Django 3.2.4 on 2021-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_auto_20210928_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "功能卡片"),
                    ("LIST", "列表"),
                    ("SHEET", "表单"),
                    ("CHART", "图表"),
                    ("GROUP", "分组"),
                ],
                max_length=32,
                verbose_name="页面类型",
            ),
        ),
        migrations.AlterField(
            model_name="pagecomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "功能组件"),
                    ("LIST", "列表组件"),
                    ("SHEET", "表单组件"),
                    ("CHART", "图表"),
                ],
                max_length=32,
                verbose_name="表单组件/列表组件/功能卡片",
            ),
        ),
    ]
