# Generated by Django 3.2.4 on 2021-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_auto_20211028_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageComponentCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="收藏的用户")),
                ("component_id", models.IntegerField(verbose_name="组件id")),
                ("page_id", models.IntegerField(default=0, verbose_name="页面id")),
                ("project_key", models.CharField(max_length=128, verbose_name="所属应用")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
            ],
            options={
                "verbose_name": "组件收藏",
                "verbose_name_plural": "组件收藏",
            },
        ),
    ]
