# Generated by Django 3.2.4 on 2021-12-27 22:25

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_pagecomponentcollection"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageOpenRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, verbose_name="页面访问token")),
                (
                    "project_key",
                    models.CharField(default="0", max_length=32, verbose_name="项目"),
                ),
                ("page_id", models.IntegerField(verbose_name="页面id")),
                ("service_id", models.IntegerField(verbose_name="页面id")),
                ("config", jsonfield.fields.JSONField(verbose_name="页面配置")),
                ("end_time", models.DateTimeField(verbose_name="截止时间")),
            ],
        ),
    ]
