# Generated by Django 3.2.4 on 2022-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_pageopenrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageopenrecord",
            name="service_id",
            field=models.IntegerField(verbose_name="服务id"),
        ),
    ]
