# Generated by Django 3.2.4 on 2022-03-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0007_alter_pageopenrecord_service_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecomponent",
            name="layout",
        ),
    ]
