# Generated by Django 3.2.4 on 2022-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0008_remove_pagecomponent_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecomponent",
            name="layout",
            field=models.JSONField(default={}, verbose_name="组件布局"),
        ),
    ]
