# Generated by Django 3.2.4 on 2022-03-29 13:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0009_pagecomponent_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="component_list",
            field=jsonfield.fields.JSONField(default=[], verbose_name="页面表层组件id列表"),
        ),
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "功能卡片"),
                    ("LIST", "列表"),
                    ("SHEET", "表单"),
                    ("CHART", "图表"),
                    ("GROUP", "分组"),
                    ("CUSTOM", "自定义"),
                ],
                max_length=32,
                verbose_name="页面类型",
            ),
        ),
        migrations.AlterField(
            model_name="pagecomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "功能组件"),
                    ("FUNCTION_GROUP", "功能组"),
                    ("LIST", "列表组件"),
                    ("SHEET", "表单组件"),
                    ("CHART", "图表"),
                    ("RICHTEXT", "图文"),
                    ("LINK", "链接组件"),
                    ("LINK_GROUP", "外部链接组"),
                    ("TAB", "选项卡"),
                ],
                max_length=32,
                verbose_name="表单组件/列表组件/功能卡片",
            ),
        ),
    ]
