# Generated by Django 3.2.4 on 2021-10-22 12:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0049_alter_state_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultfield",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="defaultfield",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
        migrations.AddField(
            model_name="field",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="field",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
        migrations.AddField(
            model_name="taskfieldschema",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="taskfieldschema",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
    ]
