# Generated by Django 3.2.4 on 2021-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0050_auto_20211022_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="show_all_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在全部流程中展示"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="show_my_create_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在我的发起中展示"),
        ),
        migrations.AddField(
            model_name="workflowversion",
            name="show_all_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在全部流程中展示"),
        ),
        migrations.AddField(
            model_name="workflowversion",
            name="show_my_create_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在我的发起中展示"),
        ),
    ]
