# Generated by Django 3.2.4 on 2022-02-24 16:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0052_auto_20211203_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultfield",
            name="num_range",
            field=jsonfield.fields.JSONField(
                default=[], verbose_name="数据范围, 只针对多选相关的情况"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="num_range",
            field=jsonfield.fields.JSONField(
                default=[], verbose_name="数据范围, 只针对多选相关的情况"
            ),
        ),
        migrations.AddField(
            model_name="taskfieldschema",
            name="num_range",
            field=jsonfield.fields.JSONField(
                default=[], verbose_name="数据范围, 只针对多选相关的情况"
            ),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="num_range",
            field=jsonfield.fields.JSONField(
                default=[], verbose_name="数据范围, 只针对多选相关的情况"
            ),
        ),
    ]
