# Generated by Django 3.2.4 on 2022-04-15 15:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0053_auto_20220224_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="extras",
            field=jsonfield.fields.JSONCharField(
                blank=True, default={}, max_length=900, null=True, verbose_name="额外信息"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "开始节点(圆形)"),
                    ("NORMAL", "普通节点"),
                    ("SIGN", "会签节点"),
                    ("APPROVAL", "审批节点"),
                    ("TASK", "自动节点"),
                    ("TASK-SOPS", "标准运维节点"),
                    ("DATA-PROC", "数据处理节点"),
                    ("ROUTER", "分支网关节点(菱形)"),
                    ("ROUTER-P", "并行网关节点"),
                    ("COVERAGE", "汇聚网关节点"),
                    ("END", "结束节点(圆形)"),
                    ("DATA-QUERY", "数据查询节点"),
                ],
                default="NORMAL",
                max_length=32,
                verbose_name="状态类型",
            ),
        ),
    ]
