# Generated by Django 3.2.4 on 2021-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户组名称")),
                ("users", models.JSONField(default={}, verbose_name="用户列表")),
                ("group_id", models.IntegerField(default=0, verbose_name="用户组ID")),
                ("action_configs", models.JSONField(default={}, verbose_name="权限配置")),
                ("data_configs", models.JSONField(default={}, verbose_name="权限配置")),
                (
                    "project_key",
                    models.CharField(default=0, max_length=32, verbose_name="项目key"),
                ),
            ],
            options={
                "verbose_name": "用户组",
                "verbose_name_plural": "用户组",
            },
        ),
    ]
