# Generated by Django 3.2.4 on 2021-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="desc",
            field=models.CharField(default="", max_length=255, verbose_name="描述"),
        ),
    ]
