# Generated by Django 3.2.4 on 2021-10-22 15:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0031_alter_taskfield_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfield",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="taskfield",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
    ]
