// 表单字段类型映射
export const FIELDS_TYPES_MAPS = {
  STRING: '单行文本',
  TEXT: 'Textarea',
  INT: '数字',
  DATE: '日期',
  DATETIME: '时间',
  TABLE: '表格',
  SELECT: '单选下拉框',
  INPUTSELECT: '可输入单选下拉框',
  MULTISELECT: '多选下拉框',
  CHECKBOX: '复选框',
  RADIO: '单选框',
  MEMBER: '单选人员选择',
  MEMBERS: '多选人员选择',
  RICHTEXT: '富文本',
  FILE: '附件上传',
  IMAGE: '图片上传',
  LINK: '链接',
  'AUTO-NUMBER': '自动编号',
  DESC: '描述文本',
  FORMULA: '计算控件',
};
