ADD_STATE = "ADD"
UPDATE_STATE = "EDIT"
DELETE_STATE = "DELETE"
DETAIL_STATE = "DETAIL"
EXPORT_STATE = "EXPORT"
IMPORT_STATE = "IMPORT"

VALUE_FROM_FIELD = "field"
VALUE_FROM_CONST = "const"

INCREMENT = "increment"
REDUCTION = "reduction"

FIELD_INCREMENT = "field_increment"
FIELD_REDUCTION = "field_reduction"

SYSTEM = "system"
APPROVER = "approver"
LEADER = "leader"
DEPARTMENT = "department"

PARAMS_TYPE = [
    VALUE_FROM_FIELD,
    FIELD_INCREMENT,
    FIELD_REDUCTION,
    LEADER,
    DEPARTMENT,
]
