# Generated by Django 3.2.4 on 2021-09-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_projectsettings_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("BLUE", "蓝色"), ("GREEN", "绿色"), ("ORANGE", "橙色")],
                        default="BLUE",
                        max_length=32,
                        verbose_name="主题色",
                    ),
                ),
                (
                    "workflow_prefix",
                    models.CharField(max_length=32, verbose_name="流程前缀"),
                ),
                (
                    "project_key",
                    models.CharField(default=0, max_length=32, verbose_name="产品"),
                ),
            ],
            options={
                "verbose_name": "应用设置",
                "verbose_name_plural": "应用设置",
            },
        ),
    ]
