# Generated by Django 3.2.4 on 2021-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_projectconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="publish_status",
            field=models.CharField(
                choices=[("RELEASED", "已发布"), ("UNRELEASED", "未发布"), ("DRAFT", "草稿")],
                db_index=True,
                default="UNRELEASED",
                max_length=32,
                verbose_name="应用状态",
            ),
        ),
    ]
