# Generated by Django 3.2.4 on 2021-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_project_publish_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="version_number",
            field=models.CharField(default="", max_length=64, verbose_name="当前绑定项目版本"),
        ),
    ]
