# Generated by Django 3.2.4 on 2021-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_project_version_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="publish_time",
            field=models.DateTimeField(null=True, verbose_name="发布时间时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="publish_status",
            field=models.CharField(
                choices=[("RELEASED", "已发布"), ("UNRELEASED", "未发布"), ("DRAFT", "草稿")],
                db_index=True,
                default="UNRELEASED",
                max_length=32,
                verbose_name="项目状态",
            ),
        ),
    ]
