# Generated by Django 3.2.4 on 2021-10-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_auto_20210924_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("RELEASED", "已发布"),
                    ("UNRELEASED", "未发布"),
                    ("CHANGED", "已变更未发布"),
                    ("RELEASING", "发布中"),
                ],
                db_index=True,
                default="UNRELEASED",
                max_length=32,
                verbose_name="项目状态",
            ),
        ),
    ]
