# Generated by Django 3.2.4 on 2021-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_project_publish_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_code",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="app_secret",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.JSONField(default={}, max_length=64, verbose_name="负责人"),
        ),
    ]
