# Generated by Django 3.2.4 on 2021-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_auto_20211109_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rating_manager_id",
            field=models.IntegerField(default=0, verbose_name="分级管理员id"),
        ),
    ]
