# Generated by Django 3.2.4 on 2022-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_project_rating_manager_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_owner",
            field=models.JSONField(default={}, max_length=64, verbose_name="数据管理用户组成员"),
        ),
        migrations.AddField(
            model_name="project",
            name="user_group_id",
            field=models.IntegerField(default=0, verbose_name="数据管理用户组id"),
        ),
    ]
