# Generated by Django 3.2.4 on 2022-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_project_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.CharField(
                error_messages={"unique": "该应用标识已被使用，请更换"},
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="项目唯一标识",
            ),
        ),
    ]
