# Generated by Django 3.2.4 on 2021-10-22 15:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0065_auto_20211014_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfield",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="taskfield",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
        migrations.AddField(
            model_name="ticketfield",
            name="mandatory_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的必填条件"),
        ),
        migrations.AddField(
            model_name="ticketfield",
            name="read_only_conditions",
            field=jsonfield.fields.JSONField(default={}, verbose_name="字段的只读条件"),
        ),
        migrations.AlterField(
            model_name="status",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "开始节点(圆形)"),
                    ("NORMAL", "普通节点"),
                    ("SIGN", "会签节点"),
                    ("APPROVAL", "审批节点"),
                    ("TASK", "自动节点"),
                    ("TASK-SOPS", "标准运维节点"),
                    ("DATA-PROC", "数据处理节点"),
                    ("ROUTER", "分支网关节点(菱形)"),
                    ("ROUTER-P", "并行网关节点"),
                    ("COVERAGE", "汇聚网关节点"),
                    ("END", "结束节点(圆形)"),
                ],
                default="NORMAL",
                max_length=32,
                verbose_name="节点类型类型",
            ),
        ),
    ]
