# Generated by Django 3.2.4 on 2021-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0066_auto_20211022_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="show_all_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在全部流程中展示"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="show_my_create_workflow",
            field=models.BooleanField(default=True, help_text="单据是否在我的发起中展示"),
        ),
    ]
