# Generated by Django 3.2.4 on 2021-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0002_operatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255, verbose_name="日志内容")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("task_id", models.IntegerField(verbose_name="发布任务ID")),
            ],
        ),
    ]
