# Generated by Django 3.2.4 on 2021-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0003_publishlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "未开始"),
                            ("RUNNING", "正在发布"),
                            ("FINISHED", "发布成功"),
                            ("FAILED", "发布失败"),
                        ],
                        default="CREATED",
                        max_length=32,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "project_key",
                    models.CharField(default=0, max_length=32, verbose_name="项目key"),
                ),
            ],
        ),
    ]
