# Generated by Django 3.2.4 on 2022-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0004_publishtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectWhite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("WORKSHEET", "表单"), ("FUNCTION", "功能")],
                        max_length=32,
                        verbose_name="资源类型",
                    ),
                ),
                ("value", models.IntegerField(max_length=1000, verbose_name="资源id")),
                (
                    "project_key",
                    models.CharField(max_length=32, verbose_name="所属项目唯一标识"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        default="2099-12-12 00:00", verbose_name="授权截止日期"
                    ),
                ),
                ("granted_project", models.JSONField(verbose_name="被授权项目唯一标识")),
            ],
        ),
    ]
