# Generated by Django 3.2.4 on 2022-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0005_projectwhite"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectversion",
            name="worksheet_event",
            field=models.JSONField(default={}, verbose_name="表单触发事件"),
            preserve_default=False,
        ),
    ]
