# Generated by Django 3.2.4 on 2021-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0031_auto_20210621_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADD", "添加"),
                    ("EDIT", "编辑"),
                    ("DELETE", "删除"),
                    ("IMPORT", "导入"),
                    ("DETAIL", "详情"),
                ],
                default="ADD",
                max_length=64,
                verbose_name="服务属性",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="key",
            field=models.CharField(
                default="DEFAULT", max_length=64, verbose_name="服务类型"
            ),
        ),
    ]
