# Generated by Django 3.2.4 on 2021-09-29 19:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0032_auto_20210921_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="worksheet_ids",
            field=jsonfield.fields.JSONField(
                blank=True, default=[], max_length=64, null=True, verbose_name="绑定的表单列表"
            ),
        ),
    ]
