# Generated by Django 3.2.4 on 2021-11-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0033_service_worksheet_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="action_id",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
