# Generated by Django 3.2.4 on 2021-11-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0034_service_action_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="action_id",
        ),
    ]
