# Generated by Django 3.2.4 on 2021-12-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0035_remove_service_action_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADD", "添加"),
                    ("EDIT", "编辑"),
                    ("DELETE", "删除"),
                    ("IMPORT", "导入"),
                    ("DETAIL", "详情"),
                    ("EXPORT", "导出"),
                ],
                default="ADD",
                max_length=64,
                verbose_name="服务属性",
            ),
        ),
    ]
