# Generated by Django 3.2.4 on 2022-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0037_periodictask"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictask",
            name="total_run_count",
            field=models.IntegerField(default=0, verbose_name="执行次数"),
        ),
    ]
