# Generated by Django 3.2.4 on 2022-02-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0038_periodictask_total_run_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodictask",
            options={"verbose_name": "服务周期任务配置表", "verbose_name_plural": "服务周期任务配置表"},
        ),
    ]
