# Generated by Django 3.2.4 on 2022-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0041_auto_20220330_1414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("NO_RULE", "无触发规则"),
                    ("PERIOD", "周期触发"),
                    ("WORKSHEET_RECORD", "记录更新触发"),
                ],
                default="NO_RULE",
                max_length=64,
                verbose_name="自动化触发规则类型",
            ),
        ),
    ]
